service: ws-serverless

provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
#  stage: dev
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:DescribeTable
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  hello:
    handler: handler.todo
    events:
      - http: ANY api

# you can add CloudFormation resource templates here
resources:
  Resources:
    testServerless:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wsServerless
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: text
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: text
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
